### ISSUE TITLE
Add chosen photos to hero slider

### ISSUE THREAD

**Issue by InPen** [NewEconomyCoalition/neweconomycoalition.github.io#10]
@r3n3p3r3z will choose three photos from this folder and @InPen will add them.

https://drive.google.com/drive/folders/0BwHUo-RMEnrHcWstZ3FBUHkwelk?usp=sharing

**Comment by r3n3p3r3z** [comment]
https://drive.google.com/drive/folders/0BwHUo-RMEnrHcWstZ3FBUHkwelk?usp=sharing

**Comment by r3n3p3r3z** [comment]
Need to add one more. Doing that now.
