### ISSUE TITLE
[Page Redesign] Fix Donate widget

### ISSUE THREAD

**Issue by InPen** [NewEconomyCoalition/neweconomycoalition.github.io#4]
Rename the About page to Donate. Remove all content, except the sub nav bar, and add this code:

`<script src='https://actionnetwork.org/widgets/v2/fundraising/support-necs-work-building-a-new-economy-2?format=js&source=widget'></script><div id='can-fundraising-area-support-necs-work-building-a-new-economy-2' style='width: 100%'><!-- this div is the target for our HTML insertion --></div>`

**Comment by r3n3p3r3z** [comment]
`<script src='https://actionnetwork.org/widgets/v2/fundraising/support-necs-work-building-a-new-economy-2?format=js&source=widget'></script><div id='can-fundraising-area-support-necs-work-building-a-new-economy-2' style='width: 100%'><!-- this div is the target for our HTML insertion --></div>`

**Comment by r3n3p3r3z** [comment]
There's a problem with this widget not properly loading. On hold for now.

**Comment by r3n3p3r3z** [comment]
Somehow, it fixed itself.....???
