### ISSUE TITLE
[Page Redesign] Update "Contact" page

### ISSUE THREAD

**Issue by InPen** [NewEconomyCoalition/neweconomycoalition.github.io#5]
Remove all content. Leave that sub-nav bar. Replace content with this:

`<link href='https://actionnetwork.org/css/style-embed.css' rel='stylesheet' type='text/css' /><script src='https://actionnetwork.org/widgets/v2/form/join-our-e-list?format=js&source=widget'></script><div id='can-form-area-join-our-e-list' style='width: 100%'><!-- this div is the target for our HTML insertion --></div>`

**Comment by r3n3p3r3z** [comment]
`<link href='https://actionnetwork.org/css/style-embed.css' rel='stylesheet' type='text/css' /><script src='https://actionnetwork.org/widgets/v2/form/join-our-e-list?format=js&source=widget'></script><div id='can-form-area-join-our-e-list' style='width: 100%'><!-- this div is the target for our HTML insertion --></div>`

**Comment by r3n3p3r3z** [comment]
Fix the widget

**Comment by r3n3p3r3z** [comment]
Fix the widget

**Comment by r3n3p3r3z** [comment]
FIXED!
