### ISSUE TITLE
Map out the report into sections

### ISSUE THREAD

**Issue by InPen** [NewEconomyCoalition/neweconomycoalition.github.io#7]
- [x] Plan out the formatting on paper
- [x] Indicate formatting using markdown
- [x] Generate the html code

**Comment by r3n3p3r3z** [comment]
https://docs.google.com/document/d/1PmKWQmjoxtU2SfP1ZRnZSyx5KySn6VxWkh1o_keOP_c/edit

**Comment by r3n3p3r3z** [comment]
Almost done. Need to finish markdowning the report but most of it has been posted.
